### ISSUE TITLE
Art Spike Title

### ISSUE THREAD

**Issue by esmesh** [Mesh-IGM/scrum_project_sample#5]
Summary

#### Task List
- [ ] Solution tasks are specified
------------
#### Solution Tasks: 
- [ ] **Specific** things that need to be done
------------
- [ ] Story Points Assigned
- [ ] Label Assigned
- [ ] Milestone & Due Date Assigned
- [ ] Art Story Assigned to Owner
- [ ] Screenshots Posted & Attached to Card
- [ ] Review completed
- [ ] Finalized Asset is Uploaded to Discord
