### ISSUE TITLE
Spike Title

### ISSUE THREAD

**Issue by esmesh** [Mesh-IGM/scrum_project_sample#7]
As a [developer], I want to [task], so that [objective].

#### Acceptance Criteria: 
* Given (how things begin), when (action taken), then (outcome of taking action).
------------
#### Task List
- [ ] Acceptance criteria are defined
- [ ] Solution tasks are specified
------------
#### Solution Tasks: 
- [ ] **Specific** things that need to be done
------------
- [ ] Label Assigned
- [ ] Milestone & Due Date Assigned
- [ ] Spike Assigned to Owner
- [ ] Documentation updated
- [ ] Spike passes all Acceptance Criteria
- [ ] Review completed
