### ISSUE TITLE
User Story Title

### ISSUE THREAD

**Issue by esmesh** [Mesh-IGM/scrum_project_sample#8]
As a [user], I want to [task], so that [objective].

#### Acceptance Criteria: 
* Given (how things begin), when (action taken), then (outcome of taking action).
------------
#### Task List
- [ ] Acceptance criteria are defined
- [ ] Solution tasks are specified
------------
#### Solution Tasks: 
- [ ] **Specific** things that need to be done
------------
- [ ] Story Points Assigned
- [ ] Label Assigned
- [ ] Milestone & Due Date Assigned
- [ ] Story Assigned to Owner
- [ ] Feature branch is created
- [ ] Solution is code complete
- [ ] Code is commented
- [ ] Design Doc is updated
- [ ] Any additional documentation is created
- [ ] User story passes all Acceptance Criteria
- [ ] Pull Request created & Reviews requested
- [ ] Review completed with both Keyboard & Gamepad
- [ ] Code Review completed
- [ ] Non-Assignee test completed
- [ ] Feature branch merged into `dev`
- [ ] Feature branch deleted
